title: "ICX532"
description: "Repositório para a disciplina ICX532 – Introdução a Ciência de Dados, do curso de Especialização em Ciência de Dados da UFMG"
baseurl: "/ICX532"
url: "https://urielmoreirasilva.github.io"
remote_theme: just-the-docs/just-the-docs
